### ISSUE TITLE
udp2raw screen on server side keeps terminating!

### ISSUE THREAD

**Issue by Iman-Sh** [wangyu-/udp2raw-tunnel#532]
Hi every one, i'm using udp2raw to tunnel both of my servers using screen command and it works amazing but the tunnel in server side keeps terminating a lot and i have to run the command again to make to tunnel work, so is there a way to automatically restart the server side tunnel when udp2raw screen gets terminated? 
and how can i figure out what is causing the termination? is there any log?

`screen ./udp2raw_amd64 -s -l0.0.0.0:4096 -r127.0.0.1:7777 -k "pass" --raw-mode icmp --log-level 5 -a`

`screen ./udp2raw_amd64 -c -l0.0.0.0:3333 -r"serverIp":4096  -k "pass" --raw-mode icmp --log-level 5 -a`

please let me know if you need more info.

**Comment by jearton** [comment]
You can use the docker image: [jearton1024/udp2raw](https://hub.docker.com/r/jearton1024/udp2raw)

**Comment by Iman-Sh** [comment]
> You can use the docker image: [jearton1024/udp2raw](https://hub.docker.com/r/jearton1024/udp2raw)

ty for your comment, i used the container with this command on server side:
`docker run -d  \
--name udp2raw_client \
--cap-add NET_ADMIN \
-p 4096:4096/udp \
-p 7777:7777/udp \
-e LISTEN_PORT=4096 \
jearton1024/udp2raw:latest  \
-s -l0.0.0.0:4096 \
-r127.0.0.1:7777\
-k "pswd" \
--raw-mode icmp -a`
looks ok based on the info that it prints but client cant reach the server and keeps sending handshake and server gets nothing.
![1](https://github.com/wangyu-/udp2raw/assets/26247694/6afaadfe-4916-4ecc-acd3-16987d48e60a)

**Comment by jearton** [comment]
@Iman-Sh  My best pracetice #531

## First start the server-side

Caution: you should use `host` network on the server-side

use docker compose

```yml
services:
  udp2raw_server:
    image: jearton1024/udp2raw:latest
    container_name: udp2raw_server
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - LISTEN_PORT= 4096
    command: >
      -s
      -l0.0.0.0:4096
      -r127.0.0.1:32884
      -k "<password>"
      --raw-mode faketcp
      --fix-gro
      -a
```

or user docker cli

```bash
docker run -d \
  --name udp2raw_server \
  --restart unless-stopped \
  --network host \
  --cap-add NET_ADMIN \
  -e LISTEN_PORT=4096 \
  jearton1024/udp2raw:latest \
  -s \
  -l0.0.0.0:4096 \
  -r127.0.0.1:32884 \
  -k "<password>" \
  --raw-mode faketcp \
  --fix-gro \
  -a
```

Note that 32884 is the wireguard peer listen port.

## Then start the client-side

use docker compose

```yaml
services:
  udp2raw_client:
    image: jearton1024/udp2raw:latest
    container_name: udp2raw_client
    restart: unless-stopped
    ports: 
      - 51820:51820
    cap_add:
      - NET_ADMIN
    environment:
      - LISTEN_PORT=51820
    command: >
      -c
      -l0.0.0.0:51820
      -r<remote ip>:4096
      -k "<password>"
      --raw-mode faketcp
      -a
```

or user docker cli

```bash
docker run -d \
  --name udp2raw_client \
  --restart unless-stopped \
  -p 51820:51820 \
  --cap-add NET_ADMIN \
  -e LISTEN_PORT=51820 \
  jearton1024/udp2raw:latest \
  -c \
  -l0.0.0.0:51820 \
  -r<remote host>:4096 \
  -k "<password>" \
  --raw-mode faketcp \
  --fix-gro \
  -a
```
